const {overview,chapterNav,visual}=require('./desktop-layout.cjs');const fs=require('fs');const {header,footer}=require('./site-shell.cjs');
(async()=>{const {marked}=await import(require.resolve('marked'));
const measurement=fs.readFileSync('docs/measurements.md','utf8').replaceAll('entscheidungen-d.md','entscheidungen.html');
const photos=fs.readFileSync('sources/README.md','utf8').replace('# Bildquellen','## Bildquellen und Herkunft').replaceAll('](previews/','](../sources/previews/').replace(/## (\d+) — ([^\n]+)/g,(_,n,title)=>`<a id="foto-${n}"></a>\n### Foto ${n} · ${title}`);
fs.writeFileSync('docs/quellen-d.md',measurement+'\n'+photos);
for(const name of ['projekt','bauteile','quellen','entscheidungen','montage','mechanik','beschaffung','kosten']){
const md=fs.readFileSync(`docs/${name}-d.md`,'utf8').replace(/\[Gemeinsamer Stand, Stückliste und nächste Entscheidungen\]\(entscheidungen-d.md\)\n/,'');
let html=marked(md).replaceAll('entscheidungen-d.md','entscheidungen.html').replaceAll('montage-d.md','montage.html').replaceAll('next-features.md','https://github.com/jdistlr/garden-torch-connector/blob/main/docs/next-features.md').replaceAll('mechanik-d.md','mechanik.html').replaceAll('beschaffung-d.md','beschaffung.html').replaceAll('kosten-d.md','kosten.html').replaceAll('../web/assets/','assets/');
html=html.replace(/<h([23])>(.*?)<\/h\1>/g,(_,level,title)=>`<h${level} id="${title.replace(/<[^>]*>/g,'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}">${title}</h${level}>`);
if(name==='beschaffung'){const ids=['plate','adapter','pin','screw','tube'];const seen=new Set();html=html.replace(/<tr>\s*<td>([1-5])<\/td>/g,(all,n)=>{const id=ids[+n-1];const anchor=seen.has(id)?'':` id="${id}"`;seen.add(id);return `<tr${anchor}><td><a href="bauteile.html#${id}">${n} · Bauteil</a></td>`;});}
html=html.replace(/<table>[\s\S]*?<\/table>/g,table=>{const labels=[...table.matchAll(/<th>([\s\S]*?)<\/th>/g)].map(x=>x[1].replace(/<[^>]*>/g,'').replaceAll('&','&amp;').replaceAll('\"','&quot;'));return table.replace(/<tr>([\s\S]*?)<\/tr>|<tr id="[^"]+">([\s\S]*?)<\/tr>/g,row=>{let i=0;return row.replace(/<td>/g,()=>`<td data-label="${labels[i++]||''}">`);});});
html=html.replace(/<table>/g,'<div class="table-scroll" tabindex="0" role="region" aria-label="Tabelle, bei Bedarf seitlich scrollen"><table>').replace(/<\/table>/g,'</table></div>');
const titles={projekt:'Gartenfackel · Projekt',bauteile:'Bauteile',quellen:'Fotos & Maße',entscheidungen:'Stand & Entscheidungen',montage:'Montage & Prüfung',mechanik:'Steck-Dreh-Funktion',beschaffung:'Beschaffung',kosten:'Kostenstudie'};
html=html.replace(/<h1>.*?<\/h1>/,'');
if(name==='bauteile')html=html.replace(/<p>(<a [\s\S]*?)<\/p>/g,'<p class="part-links">$1</p>');
fs.writeFileSync(`web/${name}.html`,`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${titles[name]} · Gartenfackel</title><link rel="stylesheet" href="design.css?rev=6"><link rel="stylesheet" href="workbench.css?rev=1"></head><body class="document-page ${name==='projekt'?'project-overview':''}">${header(name)}<main class="document" id="main-content"><h1 class="page-title">${titles[name]}</h1><div class="project-context"><label>Plattenstärke <select id="thickness"><option value="5">5 mm</option><option value="8">8 mm</option><option value="9">9 mm</option></select></label><span>D-V03 · Konzept</span></div><div class="document-meta"><p>Keine Fertigungs- oder Betriebsfreigabe</p><button class="print-action" onclick="window.print()">Drucken / PDF</button></div>${name==='projekt'?overview():visual(name)}<div class="document-layout"><article>${name==='projekt'?html.slice(html.indexOf('<h2 id="im-projekt-arbeiten"')):html}</article>${chapterNav(name==='projekt'?html.slice(html.indexOf('<h2 id="im-projekt-arbeiten"')):html)}</div>${name==='kosten'?'<p data-cost-state role="status" class="cost-context">Budgetstudie mit abweichenden Teilen, ausschließlich 5 mm.</p>':''}</main>${footer()}<script src="project-state.js?rev=3"></script></body></html>`);
}
const p='web/variants.html';fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace(/<header[\s\S]*?<\/header>/,header('variants')));
})();
