import fs from 'node:fs';
import * as THREE from '../web/vendor/three.module.js';
import {parts,steps,buildParts,applyPose,vectorScene,revision} from '../web/xray-model.js';
import shell from './site-shell.cjs';
import principle from './xray-principle.cjs';
const dir='web/assets/xray-demo';fs.mkdirSync(dir,{recursive:true});
const objects=buildParts();applyPose(objects);
const camera=new THREE.PerspectiveCamera(38,900/550,1,6000);camera.position.set(650,410,620);camera.lookAt(0,0,0);fs.writeFileSync(`${dir}/assembly.svg`,vectorScene(objects,camera));
applyPose(objects,{explode:1});camera.position.set(1050,700,1050);camera.lookAt(0,10,0);fs.writeFileSync(`${dir}/exploded.svg`,vectorScene(objects,camera));applyPose(objects);
// Non-functional triangle exports of the illustrative model, NOT manufacturing CAD/STEP.
function stl(list){let text='solid XR_DEMO_NONFUNCTIONAL\n';for(const o of list)for(const mesh of o.meshes){mesh.updateWorldMatrix(true,false);const g=mesh.geometry,p=g.attributes.position,idx=g.index,n=idx?idx.count:p.count;for(let i=0;i<n;i+=3){const v=[0,1,2].map(k=>new THREE.Vector3().fromBufferAttribute(p,idx?idx.getX(i+k):i+k).applyMatrix4(mesh.matrixWorld));const norm=v[1].clone().sub(v[0]).cross(v[2].clone().sub(v[0])).normalize();text+=`facet normal ${norm.toArray().join(' ')}\nouter loop\n${v.map(p=>'vertex '+p.toArray().map(x=>x.toFixed(5)).join(' ')).join('\n')}\nendloop\nendfacet\n`;}}return text+'endsolid XR_DEMO_NONFUNCTIONAL\n';}
for(const o of objects)fs.writeFileSync(`${dir}/${o.id}.stl`,stl([o]));fs.writeFileSync(`${dir}/assembly.stl`,stl(objects));
fs.writeFileSync(`${dir}/parts.json`,JSON.stringify({revision,status:'Fictional non-functional display model; all sizes, prices and suppliers invented',units:'demo-mm',parts},null,2)+'\n');
function view(position,visible){objects.forEach(o=>o.group.visible=visible.includes(o.id));const c=new THREE.OrthographicCamera(-300,300,185,-185,1,4000);c.position.set(...position);c.lookAt(0,-10,0);return vectorScene(objects,c,760,460).replace(/<svg[^>]*>/,'').replace('</svg>','');}
for(const sheet of [1,2]){const visible=sheet===1?parts.map(p=>p.id):['base','carrier','anode','bearing','cathode','envelope','cooler'];const front=view([0,0,1000],visible),top=view([0,1000,0],visible);const title=sheet===1?'Gesamtanordnung / äußere Hülle':'Innere Baugruppen / Prinzipdarstellung';
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="420mm" height="297mm" viewBox="0 0 1400 990"><style>text{font-family:Arial,sans-serif;fill:#1b3548}.head{font-size:28px}.small{font-size:15px}.dim{font-size:17px}.warn{fill:#9c4528;font-size:18px}line,rect{stroke:#29485e;stroke-width:1;fill:none}</style><rect x="25" y="25" width="1350" height="940"/><text x="55" y="74" class="head">XR-DEMO / 01 — ${title}</text><text x="55" y="107" class="warn">FIKTIVES ANSCHAUUNGSMODELL · NICHT FUNKTIONSFÄHIG · KEINE FERTIGUNGSZEICHNUNG</text><g transform="translate(55 145)">${front}</g><text x="65" y="635" class="small">Vorderansicht · Parallelprojektion · nicht maßstäblich drucken</text><g transform="translate(845 175) scale(.62)">${top}</g><text x="850" y="490" class="small">Draufsicht · Parallelprojektion</text><line x1="${sheet===1?150:258}" y1="665" x2="${sheet===1?745:613}" y2="665"/><line x1="${sheet===1?150:258}" y1="655" x2="${sheet===1?150:258}" y2="675"/><line x1="${sheet===1?745:613}" y1="655" x2="${sheet===1?745:613}" y2="675"/><text x="335" y="694" class="dim">${sheet===1?'470 Demo-mm Gesamtbreite':'280 Demo-mm Röhrenhülle (Symbol)'}</text><text x="55" y="745" class="small">Alle Maßzahlen sind frei erfundene Visualisierungsparameter. Keine Toleranzen, Passungen oder Gewinde definiert.</text><text x="55" y="775" class="small">Keine elektrische, thermische, Vakuum- oder Strahlenschutz-Auslegung. Keine reale Herstellerreferenz.</text><text x="55" y="805" class="small">${sheet===1?'Gehäuseschale, Servicehaube und Enddeckel dienen ausschließlich der Produktdarstellung.':'Anoden- und Kathodenmodule sind vereinfachte Symbole; diese Anordnung erzeugt keine Röntgenstrahlung.'}</text><rect x="55" y="850" width="1290" height="85"/><line x1="850" y1="850" x2="850" y2="935"/><line x1="1140" y1="850" x2="1140" y2="935"/><text x="75" y="883" class="small">One More Thing / Gartenfackel-Projekt / separater Demonstrator</text><text x="75" y="914" class="small">Quelle: web/xray-model.js · reine Darstellungsgeometrie</text><text x="870" y="887" class="small">A3 · Schemazeichnung</text><text x="870" y="914" class="small">Revision XR-DEMO / 01</text><text x="1160" y="897" class="head">${sheet} / 2</text></svg>`;fs.writeFileSync(`${dir}/drawing-${sheet}.svg`,svg);}
const sections=[['overview','Übersicht'],['model','Modell & Montage'],['principle','Funktionsprinzip'],['parts','Fiktive Stückliste'],['sourcing','Fiktive Beschaffung'],['drawings','Zeichnungen'],['limits','Grenzen & Transfer']];
const nav=sections.map(([id,label])=>`<a href="#${id}" data-xr-nav>${label}</a>`).join('');
let header=shell.header('one-more-thing').replace('<a class="brand" href="projekt.html">','<a class="brand" href="one-more-thing.html">').replace('>G/</span>','>X/</span>').replace('>Gartenfackel<small>Engineering / D-V03</small>','>One More Thing<small>Röntgenstrahler / DEMO</small>').replace(/<nav class="desktop-nav"[\s\S]*?<\/nav>/,`<nav class="desktop-nav" aria-label="Demonstrator"><p class="nav-caption">XR-DEMO / ARBEITSBEREICHE</p>${nav}<p class="nav-caption">PROJEKT WECHSELN</p><a href="projekt.html">← Zur Gartenfackel</a></nav>`).replace('Geometrie geprüft.<br>Reale Freigaben offen.','Fiktives Anschauungsmodell.<br>Keine Strahlenquelle.').replace('Konzeptstand','Proof of Concept').replace(/<details class="project-menu">[\s\S]*?<\/details>/,`<details class="project-menu"><summary>One More Thing · Bereiche</summary><nav aria-label="Demonstrator mobil">${nav}<a href="projekt.html">← Zur Gartenfackel</a></nav></details>`);
const total=parts.reduce((s,p)=>s+p.price,0);
const html=`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>One More Thing · XR-DEMO</title><script type="importmap">{"imports":{"three":"./vendor/three.module.js","three/addons/":"./vendor/"}}</script><link rel="stylesheet" href="design.css?rev=6"><link rel="stylesheet" href="workbench.css?rev=3"><link rel="stylesheet" href="xray.css?rev=1"></head><body class="xray-page">${header}<main id="main-content"><section id="overview" class="xr-intro"><div><p class="eyebrow">ONE MORE THING / PROOF OF CONCEPT</p><h1>Eben noch Gartenbeleuchtung.<br>Jetzt Innenansichten.</h1><p>Gleiche Arbeitsweise. Anderes Anschauungsobjekt: ein fiktiver moderner Röntgenstrahler aus elf Baugruppen. Modell, Erklärmontage, Teileliste und Zeichnungen bleiben verbunden.</p><a class="primary-action" href="#model">Demonstrator öffnen ↓</a><a class="xr-back" href="projekt.html">Zurück zur Gartenfackel</a></div><img src="assets/xray-demo/exploded.svg" alt="Explosionsansicht der elf fiktiven Baugruppen"></section><p class="xr-warning"><strong>Nur ein Demonstrator.</strong> Alle Maße, Preise und Anbieter sind erfunden. Keine Strahlenquelle, kein realer Bauplan, keine medizinische oder technische Freigabe.</p>
<section id="model" class="xr-workspace"><div class="xr-bar"><div><p class="eyebrow">XR-DEMO / 01</p><h2>Modell & Erklärmontage</h2></div><span id="xr-status" role="status">Darstellung wird geladen …</span></div><div class="xr-desk"><div class="xr-stage"><div id="xr-viewport"><img src="assets/xray-demo/assembly.svg" alt="Statische CAD-Schemaansicht bis zum Laden des Demonstrators"><div id="xr-label" hidden></div></div><div class="xr-stage-tools"><button id="xr-interact" aria-pressed="false">Drehen / Zoomen aktivieren</button><button data-xr-view="iso">Isometrie</button><button data-xr-view="front">Vorne</button><button data-xr-view="side">Seite</button><button data-xr-view="top">Oben</button><button id="xr-reset">Zurücksetzen</button></div><p id="xr-render-note">JavaScript lädt das interaktive Modell. Ohne JavaScript bleiben Listen, Schemaansicht und Zeichnungen verfügbar.</p><div class="xr-playback"><div class="toolbar"><button id="xr-play" class="primary-action">Montage abspielen</button><button id="xr-prev" aria-label="Vorheriger Montageschritt">← Schritt</button><button id="xr-next" aria-label="Nächster Montageschritt">Schritt →</button><button id="xr-restart">Zum Anfang</button></div><label for="xr-timeline">Montagefortschritt <output id="xr-step-count">${parts.length} / ${parts.length}</output></label><input id="xr-timeline" type="range" min="0" max="${parts.length}" step="0.01" value="${parts.length}"><h3 id="xr-step-title">Gesamtanordnung</h3><p id="xr-step-text">Bauteil auswählen oder die Erklärmontage starten. Die geschlossene Hülle lässt sich ausblenden, transparent darstellen oder schematisch schneiden.</p><details><summary>Einzelnen Schritt wählen</summary><div class="xr-step-list">${steps.map((s,i)=>`<button data-xr-step="${i}">${String(i).padStart(2,'0')} · ${s.name}</button>`).join('')}</div></details></div></div>
<aside class="xr-inspector" aria-label="Modellwerkzeuge"><label for="xr-part">Bauteil untersuchen</label><select id="xr-part"><option value="">Gesamte Baugruppe</option>${parts.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select><div id="xr-part-info" hidden><h3 id="xr-part-name"></h3><p id="xr-part-detail"></p><div class="toolbar"><button id="xr-focus">Fokussieren</button><button id="xr-install">Einbauschritt</button></div><nav><a id="xr-record" href="#parts">Stücklisteneintrag →</a><a id="xr-source" href="#sourcing">Beschaffungsbeispiel →</a><a id="xr-part-stl" href="assets/xray-demo/assembly.stl">Demo-Netz STL ↓</a></nav></div><div class="xr-options"><label><input id="xr-solo" type="checkbox"> Nur gewähltes Teil</label><label><input id="xr-transparent" type="checkbox"> Gehäuse transparent</label><label><input id="xr-cut" type="checkbox"> Schematischer Halbschnitt</label><label><input id="xr-dimensions" type="checkbox"> Demo-Abmessungen</label></div><label for="xr-explode">Baugruppen auseinanderziehen</label><input id="xr-explode" type="range" min="0" max="1" step="0.01" value="0"><p class="xr-caption">Halbschnitt: offene Schnittkanten, keine Material- oder Abschirmungsbewertung.</p><details><summary>Teile ein- und ausblenden</summary><div class="xr-visibility">${parts.map(p=>`<label><input type="checkbox" data-xr-visible="${p.id}" checked> ${p.name}</label>`).join('')}</div></details><details><summary>Ansicht teilen & exportieren</summary><button id="xr-share">Ansichtslink kopieren</button><button id="xr-png">PNG mit Demo-Kennzeichnung</button><a href="assets/xray-demo/assembly.stl">Gesamtes Demo-Netz STL ↓</a><div id="xr-share-result" hidden><label for="xr-link">Ansichtslink</label><input id="xr-link" readonly><p id="xr-share-status" role="status"></p></div><p class="xr-caption">STL enthält die illustrativen Netze, keine fertigungstauglichen CAD-Körper oder STEP-Daten.</p></details></aside></div></section>
${principle.markup()}<section id="parts" class="xr-section"><p class="eyebrow">01 / FIKTIVE STÜCKLISTE</p><h2>Elf Baugruppen. Eine Modellquelle.</h2><p>Jede Zeile führt zur Geometrie und zum zugehörigen Erklärschritt. Maßangaben in erfundenen „Demo-mm“; Materialnamen beschreiben nur die Optik.</p><div class="table-scroll"><table><thead><tr><th>Pos. / Bauteil</th><th>Demo-Maß</th><th>Optik</th><th>Menge</th><th>Untersuchen</th></tr></thead><tbody>${parts.map((p,i)=>`<tr id="part-${p.id}"><td>${String(i+1).padStart(2,'0')} · ${p.name}</td><td>${p.size}</td><td>${p.material}</td><td>1</td><td><button data-xr-select="${p.id}">Im Modell</button> <a href="#source-${p.id}">Beschaffung</a></td></tr>`).join('')}</tbody></table></div></section>
<section id="sourcing" class="xr-section"><p class="eyebrow">02 / ERFUNDENE BESCHAFFUNG</p><h2>Eine Stückliste kann zur Entscheidung führen.</h2><p>Diese Anbieter existieren hier nur als Beispieldatensätze. Keine Händlerlinks, Kontakte, Lagerbestände oder Bestellungen. Euro-Werte sind frei erfundene Rechengrößen.</p><div class="table-scroll"><table><thead><tr><th>Bauteil</th><th>Erfundener Anbieter</th><th>Fiktiver Einzelpreis</th><th>Hinweis</th></tr></thead><tbody>${parts.map(p=>`<tr id="source-${p.id}"><td><a href="#part-${p.id}">${p.name}</a></td><td>${p.source}</td><td>${p.price.toFixed(2).replace('.',',')} €</td><td>Demo-Datensatz · nicht bestellbar</td></tr>`).join('')}</tbody></table></div><div class="xr-budget"><div><span>1 Demo-Satz</span><strong>${total.toLocaleString('de-DE')},00 €</strong></div><div><span>5 Demo-Sätze</span><strong>${(total*5).toLocaleString('de-DE')},00 €</strong></div><div><span>10 Demo-Sätze</span><strong>${(total*10).toLocaleString('de-DE')},00 €</strong></div></div><p class="xr-caption">Nur Mengensumme ohne Rabatt. Versand, Bearbeitung, Steuern und reale Kosten sind nicht kalkuliert. Keine Wirtschaftlichkeitsbehauptung.</p><a href="assets/xray-demo/parts.json">Fiktive Stückliste als JSON ↓</a></section>
<section id="drawings" class="xr-section"><p class="eyebrow">03 / ZEICHNUNGSAUSSCHNITTE</p><h2>Vom Modell zur lesbaren Ansicht.</h2><p>Zwei A3-Schemablätter aus derselben Darstellungsgeometrie. Keine Fertigungszeichnungen, keine Toleranzen und keine freigegebenen Maße.</p><div class="xr-drawings">${[1,2].map(i=>`<figure><a href="assets/xray-demo/drawing-${i}.svg" target="_blank" rel="noopener"><img loading="lazy" src="assets/xray-demo/drawing-${i}.svg" alt="Schemablatt ${i}: ${i===1?'Gesamtanordnung':'innere Baugruppen'}"></a><figcaption>0${i} / ${i===1?'Gesamtanordnung':'Innere Baugruppen'} · <a href="assets/xray-demo/drawing-${i}.svg" download>SVG herunterladen</a></figcaption></figure>`).join('')}</div></section>
<section id="limits" class="xr-section"><p class="eyebrow">04 / WAS DER PROOF OF CONCEPT ZEIGT</p><h2>Die Arbeitsweise ist übertragbar. Die Freigabe nicht.</h2><div class="xr-limits"><div><h3>Demonstriert</h3><p>Gemeinsame Modellquelle, Bauteilkontext, schrittweise Erklärbewegung, transparente Hülle, schematischer Schnitt, Ansichtslink, PNG/STL, fiktive Beschaffung und abgeleitete Zeichnungsansichten.</p></div><div><h3>Bewusst nicht enthalten</h3><p>Elektronenoptik, Hochspannung, Vakuumprozess, Strahlenschutz, Wärmehaushalt, Dosis, Sicherheitssysteme, Normkonformität, reale Herstellbarkeit oder Kollisionsfreigabe. Dieses Modell kann keine Röntgenstrahlung erzeugen.</p></div></div><a class="primary-action" href="projekt.html">Zurück zum Gartenfackel-Projekt →</a></section></main><footer class="site-footer"><span>One More Thing · ${revision} · Fiktion, kein Produkt</span><a href="projekt.html">Gartenfackel / D-V03</a></footer><script type="module" src="xray.js?rev=3"></script></body></html>`;
fs.writeFileSync('web/one-more-thing.html',html);
console.log(`XR-DEMO: ${parts.length} fictional parts, STL display meshes and 2 SVG schema sheets generated; total demo sum ${total}.`);
