import * as THREE from 'three';
import {poseAt,stepAt} from './montage-d.js';
const $=s=>document.querySelector(s);
const names={plate:'Grundplatte',adapter:'Massive Aufnahme',pin:'Querstift',screw:'Senkschraube',tube:'Fackelrohr'};
const info={plate:['150 × 150 mm; Stärke nach Auswahl. Nutzerschätzung / Konzept.','Ebenheit, Senkung und reale Kopfkontur prüfen.',4],adapter:['Ø24 × 50; direktes M8-Sackloch. Konzeptmaße.','Werkstoff, tragendes Gewinde und Stiftsitz festlegen.',3],pin:['Ø4 × 21; 17 mm Überstand + 4 mm Sitz. Foto-/Konzeptannahme.','Normkandidat Ø4 × 20 weicht ab; Sicherung offen.',1],screw:['M8 × 20; idealisierte Kopfhülle.','Realen Kopf, Festigkeit und Anziehverfahren prüfen.',3],tube:['Ø27 / innen Ø25 × 180. Unbestätigter Fotoentwurf.','Schlitz, Ovalität und oberen Fackelanschluss messen.',6]};
export function mountPartInfo(){
 const select=$('#select-part');let selected=new URL(location.href).searchParams.get('part');if(!names[selected])selected='';
 const paint=()=>{selected=select.value;const panel=$('#selected-part');panel.hidden=!selected;if(!selected)return;const t=$('#thickness').value;$('#selected-name').textContent=names[selected];$('#selected-measure').textContent=info[selected][0];$('#selected-open').textContent=info[selected][1];$('#part-record').href=`bauteile.html?plate=${t}#${selected}`;$('#part-source').href=`quellen.html?plate=${t}#${selected==='pin'?'foto-09':selected==='tube'?'erste-messrunde':selected==='adapter'?'foto-14':'funktionsfragen'}`;$('#part-buy').href=`beschaffung.html?plate=${t}#${selected}`;};
 select.value=selected;paint();select.addEventListener('change',paint);document.addEventListener('platechange',paint);
 return {get:()=>select.value,set(id){select.value=id;paint();},paint};
}
export function enhanceScene(api,parts){
 const {scene,camera,controls,renderer,host,floor,key}=api;
 let selected=parts.get(),tween=null,cutItems=[],lastStep=-1,restored=false;
 const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),ghosts=new THREE.Group(),arrows=new THREE.Group();scene.add(ghosts,arrows);
 const label=document.createElement('span');label.className='scene-part-label';label.hidden=true;host.append(label);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 renderer.localClippingEnabled=true;renderer.setClearColor(0xf1f0ed);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
 floor.material.color.set(0xe5e2dc);floor.receiveShadow=true;key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-150,right:150,top:150,bottom:-150,near:1,far:800});key.shadow.bias=-.0002;key.shadow.normalBias=.08;
 // A small procedural studio is processed once; no remote texture download.
 const studio=new THREE.Scene();studio.background=new THREE.Color(0x777777);
 const room=new THREE.Mesh(new THREE.BoxGeometry(10,10,10),new THREE.MeshBasicMaterial({color:0xb5b5b5,side:THREE.BackSide}));studio.add(room);
 for(const [x,y,z,sx,sy] of [[-4,0,2,3,6],[4,1,3,3,5],[0,0,4.5,5,5]]){const panel=new THREE.Mesh(new THREE.PlaneGeometry(sx,sy),new THREE.MeshBasicMaterial({color:new THREE.Color(3,3,3),side:THREE.DoubleSide}));panel.position.set(x,y,z);panel.lookAt(0,0,0);studio.add(panel);}
 const pmrem=new THREE.PMREMGenerator(renderer);let env;
 try{env=pmrem.fromScene(studio,.08);scene.environment=env.texture;}finally{pmrem.dispose();studio.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}
 function quality(){const q=$('#scene-quality').value,low=q==='low'||(q==='auto'&&(matchMedia('(pointer: coarse)').matches||host.clientWidth<600));renderer.setPixelRatio(Math.min(devicePixelRatio,low?1.25:2));renderer.shadowMap.enabled=!low;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.needsUpdate=true;api.resize();}
 function materials(){const product=$('#scene-style').value==='product';for(const o of api.objects()){o.mesh.material.metalness=product?(o.id==='adapter'?.25:.75):.15;o.mesh.material.roughness=product?(o.id==='adapter'?.56:.32):.72;o.mesh.material.envMapIntensity=product?1:.35;o.mesh.castShadow=true;o.mesh.receiveShadow=true;}quality();}
 function fly(target,position){const to=new THREE.Vector3(...position),at=new THREE.Vector3(...target);if(reduced){camera.position.copy(to);controls.target.copy(at);controls.update();return;}tween={start:performance.now(),from:camera.position.clone(),old:controls.target.clone(),to,at};}
 function cancel(){tween=null;}
 controls.addEventListener('start',cancel);$('#interact-model').addEventListener('click',cancel);$('#zoom-model-in').addEventListener('click',cancel);$('#zoom-model-out').addEventListener('click',cancel);
 function focus(id=selected){const o=api.objects().find(o=>o.id===id);if(!o)return;api.free();o.visible=true;if(id==='tube')$('#tube').checked=true;api.refresh();const box=new THREE.Box3().setFromObject(o.mesh),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length();const d=Math.max(38,size*1.8);fly(center.toArray(),center.clone().add(new THREE.Vector3(.65,-1,.65).multiplyScalar(d)).toArray());}
 function choose(id){selected=id;parts.set(id);sync();}
 $('#select-part').addEventListener('change',()=>choose(parts.get()));$('#focus-part').onclick=()=>focus();$('#part-montage').onclick=()=>{api.step(info[selected][2]);sync();};
 let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;down=null;const r=host.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(api.objects().filter(o=>o.group.visible).map(o=>o.mesh));const hit=hits.find(h=>!$('#moving-cut').checked||plane.distanceToPoint(h.point)>=-.001);if(hit){const o=api.objects().find(o=>o.mesh===hit.object);choose(o.id);}});
 function question(q){api.free();$('#explode').value=0;$('#transparent').checked=false;$('#moving-cut').checked=false;$('#section').checked=false;$('#tube').checked=true;$('#ground').checked=true;const t=api.state().thick;
 if(q==='thread'){$('#moving-cut').checked=true;$('#cut-position').value=0;choose('screw');fly([0,0,t+10],[40,-85,t+38]);}
 if(q==='connection'){choose('pin');fly([0,0,t+35],[75,-100,t+80]);}
 if(q==='ground'){$('#ground').checked=false;choose('screw');fly([0,0,0],[30,-90,-65]);}
 if(q==='play'){$('#moving-cut').checked=true;$('#cut-position').value=0;choose('tube');fly([0,0,t+35],[45,-75,t+48]);}
 if(q==='measure'){choose('tube');$('#dimensions').checked=true;fly([0,0,80],[195,-245,245]);}
 $('#question-note').textContent={thread:'Sackloch und Schraubenhülle: keine Darstellung tragender Gewindeflanken.',connection:'Stift und Schlitz bilden den Steck-Dreh-Weg. Keine Rastung nachgewiesen.',ground:'Nominal 0,2 mm Kopfrückstand. Am realen beschichteten Teil prüfen.',play:'Nominales Durchmesserspiel 1 mm (Ø25 innen / Ø24 Kopf), axiales Nutspiel 2 mm. Keine Istmessung.',measure:'Beschriftungen sind Konzeptmaße. Bestätigte Werte fehlen; Messliste und Originalfotos beim gewählten Bauteil öffnen.'}[q];api.refresh();}
 document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>question(b.dataset.question));
 function disposeAux(){for(const o of cutItems){o.group.remove(o.back,o.front);scene.remove(o.cap);o.back.material.dispose();o.front.material.dispose();o.cap.geometry.dispose();o.cap.material.dispose();}cutItems=[];ghosts.children.slice().forEach(o=>{ghosts.remove(o);o.material.dispose();});}
 function rebuild(){disposeAux();api.objects().forEach((o,i)=>{o.mesh.renderOrder=20;o.lines.renderOrder=21;
  const base={depthWrite:false,depthTest:false,colorWrite:false,stencilWrite:true,stencilFunc:THREE.AlwaysStencilFunc,clippingPlanes:[plane]};
  const back=new THREE.Mesh(o.full,new THREE.MeshBasicMaterial({...base,side:THREE.BackSide,stencilFail:THREE.IncrementWrapStencilOp,stencilZFail:THREE.IncrementWrapStencilOp,stencilZPass:THREE.IncrementWrapStencilOp}));
  const front=new THREE.Mesh(o.full,new THREE.MeshBasicMaterial({...base,side:THREE.FrontSide,stencilFail:THREE.DecrementWrapStencilOp,stencilZFail:THREE.DecrementWrapStencilOp,stencilZPass:THREE.DecrementWrapStencilOp}));back.renderOrder=1+i*3;front.renderOrder=2+i*3;o.group.add(back,front);
  const cap=new THREE.Mesh(new THREE.PlaneGeometry(800,800),new THREE.MeshBasicMaterial({color:o.id==='adapter'?0x747b80:0xc8c9c6,side:THREE.DoubleSide,stencilWrite:true,stencilRef:0,stencilFunc:THREE.NotEqualStencilFunc,stencilFail:THREE.ReplaceStencilOp,stencilZFail:THREE.ReplaceStencilOp,stencilZPass:THREE.ReplaceStencilOp}));cap.rotation.x=Math.PI/2;cap.renderOrder=3+i*3;cap.onAfterRender=()=>renderer.clearStencil();scene.add(cap);cutItems.push({...o,back,front,cap});
  const ghost=new THREE.Mesh(o.full,new THREE.MeshBasicMaterial({color:0x697078,wireframe:true,transparent:true,opacity:.1,depthWrite:false}));ghost.userData.id=o.id;ghosts.add(ghost);
 });materials();sync();if(!restored){restored=true;restore();}}
 function sync(){const s=api.state(),cut=$('#moving-cut').checked&&!s.montage;plane.constant=-Number($('#cut-position').value);$('#cut-output').textContent=Number($('#cut-position').value).toFixed(1)+' mm';$('#cut-position').disabled=!cut;$('#moving-cut').disabled=s.montage;document.querySelectorAll('[data-question],#focus-part').forEach(e=>e.disabled=s.montage);
 if(cut){$('#section').checked=false;$('#transparent').checked=false;}$('#section').disabled=cut||s.montage;$('#transparent').disabled=cut;
 for(const o of api.objects()){if(cut){o.mesh.geometry=o.full;o.lines.geometry=o.fullEdges;o.mesh.material.transparent=false;o.mesh.material.opacity=1;o.mesh.material.depthWrite=true;}o.mesh.material.clippingPlanes=cut?[plane]:null;o.lines.material.clippingPlanes=cut?[plane]:null;const action=s.montage?['','pin','adapter','screw','plate','tube','tube','tube'][stepAt(s.progress)]:selected;const active=o.id===action;o.lines.material.color.set(active?0xa94023:0x465565);o.lines.material.opacity=active?.95:.35;o.lines.visible=active||$('#edges').checked;o.mesh.material.emissive.set(active?0x291007:0x000000);}
 for(const o of cutItems){o.back.visible=o.front.visible=cut;o.cap.visible=cut&&o.group.visible;o.cap.position.y=-plane.constant;}
 ghosts.visible=s.montage&&$('#show-ghost').checked;arrows.visible=s.montage&&$('#show-direction').checked;
 if(s.montage){const i=stepAt(s.progress),p=poseAt(Math.max(0,i-1),s.thick);for(const g of ghosts.children){const id=g.userData.id;g.visible=id===(['','pin','adapter','screw','plate','tube','tube','tube'][i]);g.position.set(0,id==='pin'?p.pinY:0,p[id]);g.rotation.z=id==='tube'?p.angle*Math.PI/180:0;}if(lastStep!==i){lastStep=i;arrows.children.slice().forEach(o=>{arrows.remove(o);o.traverse(c=>{c.geometry?.dispose();c.material?.dispose();});});if(i>0&&i<7){const id=['','pin','adapter','screw','plate','tube','tube'][i],o=api.objects().find(o=>o.id===id),box=new THREE.Box3().setFromObject(o.mesh),at=box.getCenter(new THREE.Vector3());at.x+=25;arrows.add(new THREE.ArrowHelper(new THREE.Vector3(0,i===1?-1:0,i===1?0:i===3?1:-1),at,30,0xa94023,7,4));}if(i===7){const pts=Array.from({length:33},(_,n)=>{const a=n/32*50*Math.PI/180;return new THREE.Vector3(Math.cos(a)*38,Math.sin(a)*38,s.thick+40);});arrows.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xa94023})));arrows.add(new THREE.ArrowHelper(new THREE.Vector3(-Math.sin(50*Math.PI/180),Math.cos(50*Math.PI/180),0),pts.at(-1),10,0xa94023,5,3));}}}else lastStep=-1;
 }
 $('#moving-cut').onchange=()=>{api.refresh();};$('#cut-position').oninput=()=>{api.refresh();};$('#scene-style').onchange=materials;$('#scene-quality').onchange=quality;$('#show-ghost').onchange=sync;$('#show-direction').onchange=sync;
 const serialize=()=>{const s=api.state(),u=new URL(location.href);u.search='';u.hash='design';const values={plate:s.thick,part:selected,mode:s.montage?'montage':'free',step:s.progress.toFixed(3),camera:camera.position.toArray().map(n=>n.toFixed(3)).join(','),target:controls.target.toArray().map(n=>n.toFixed(3)).join(','),cut:$('#moving-cut').checked?'1':'0',slice:$('#cut-position').value,section:$('#section').checked?'1':'0',transparent:$('#transparent').checked?'1':'0',explode:$('#explode').value,style:$('#scene-style').value,quality:$('#scene-quality').value,edges:$('#edges').checked?'1':'0',ground:$('#ground').checked?'1':'0',tube:$('#tube').checked?'1':'0',hidden:api.objects().filter(o=>!o.visible).map(o=>o.id).join(','),guide:$('#montage-guide').checked?'1':'0',ghost:$('#show-ghost').checked?'1':'0',direction:$('#show-direction').checked?'1':'0',dimensions:$('#dimensions').checked?'1':'0'};for(const [k,v] of Object.entries(values))if(v!=='')u.searchParams.set(k,String(v));return u.href;};
 $('#share-view').onclick=async()=>{api.pause();cancel();const value=serialize();$('#share-url').value=value;$('#share-result').hidden=false;try{await navigator.clipboard.writeText(value);$('#share-status').textContent='Ansichtslink kopiert.';}catch{$('#share-url').focus();$('#share-url').select();$('#share-status').textContent='Ansichtslink zum Kopieren ausgewählt.';}};
 function restore(){const p=new URL(location.href).searchParams;for(const id of ['section','transparent','edges','ground','tube','dimensions'])if(p.has(id))$('#'+id).checked=p.get(id)==='1';for(const [key,id] of [['guide','montage-guide'],['ghost','show-ghost'],['direction','show-direction']])if(p.has(key))$('#'+id).checked=p.get(key)==='1';$('#moving-cut').checked=p.get('cut')==='1';if(p.has('slice'))$('#cut-position').value=Math.max(-80,Math.min(80,Number(p.get('slice'))||0));if(p.has('explode'))$('#explode').value=Math.max(0,Math.min(1,Number(p.get('explode'))||0));if(['technical','product'].includes(p.get('style')))$('#scene-style').value=p.get('style');if(['auto','low','high'].includes(p.get('quality')))$('#scene-quality').value=p.get('quality');for(const o of api.objects())o.visible=!(p.get('hidden')||'').split(',').includes(o.id);if(p.get('mode')==='montage')api.step(Math.max(0,Math.min(7,Number(p.get('step'))||0)));else {api.refresh();if(['iso','side','bottom','detail'].includes(p.get('view')))api.view(p.get('view'));}document.querySelectorAll('#parts input').forEach((c,i)=>{c.checked=api.objects().filter(o=>o.id!=='tube')[i].visible;});materials();cancel();for(const [key,vec] of [['camera',camera.position],['target',controls.target]]){const a=(p.get(key)||'').split(',').map(Number);if(a.length===3&&a.every(n=>Number.isFinite(n)&&Math.abs(n)<=2000))vec.set(...a);}controls.update();}
 function exportPNG(){api.pause();cancel();tick(performance.now());renderer.render(scene,camera);const source=renderer.domElement,out=document.createElement('canvas');out.width=source.width;const band=$('#export-labels').checked?120:0;out.height=source.height+band;const ctx=out.getContext('2d');ctx.drawImage(source,0,0);if(band){ctx.fillStyle='#fcfbf9';ctx.fillRect(0,source.height,out.width,band);ctx.fillStyle='#25292d';ctx.font=`${Math.max(12,Math.min(20,out.width/38))}px sans-serif`;const s=api.state();const lines=[`D-V03 · Platte ${s.thick} mm · ${names[selected]||'Gesamtansicht'}`,s.montage?`Montage ${s.progress.toFixed(2)} / 7 · keine Rastung`:`${$('#moving-cut').checked?'Schnittebene y = '+$('#cut-position').value+' mm':'CAD-Ansicht'} · ${$('#scene-style').value==='product'?'Oberfläche visualisiert':'Technische Darstellung'}`,'Konzeptmaße · keine Fertigungs-/Betriebsfreigabe'];lines.forEach((text,i)=>ctx.fillText(text,16,source.height+30+i*30,out.width-32));}const a=document.createElement('a');a.download=`D-V03-${api.state().thick}mm-Ansicht.png`;a.href=out.toDataURL('image/png');a.click();}
 $('#snapshot').onclick=exportPNG;
 function tick(time){if(tween){const u=Math.min(1,(time-tween.start)/600),v=u*u*(3-2*u);camera.position.lerpVectors(tween.from,tween.to,v);controls.target.lerpVectors(tween.old,tween.at,v);controls.update();if(u===1)tween=null;}const o=api.objects().find(o=>o.id===selected);label.hidden=!o||!o.group.visible||api.state().montage;if(!label.hidden){const p=new THREE.Box3().setFromObject(o.mesh).getCenter(new THREE.Vector3()).project(camera);label.hidden=p.z< -1||p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1;label.textContent=names[selected];label.style.left=Math.max(10,Math.min(host.clientWidth-170,(p.x+1)*host.clientWidth/2))+'px';label.style.top=Math.max(12,Math.min(host.clientHeight-42,(1-p.y)*host.clientHeight/2))+'px';}}
 $('#reset-d').addEventListener('click',()=>{cancel();$('#moving-cut').checked=false;$('#cut-position').value=0;choose('');$('#question-note').textContent='';api.refresh();});
 return {rebuild,sync,tick,fly,cancel,restore};
}
