import * as THREE from 'three';
import {poseAt,steps,stepAt} from './montage-d.js';
import {OrbitControls} from 'three/addons/OrbitControls.js';
const $=s=>document.querySelector(s);
let montage=false, playing=false, progress=0, previousTime=null;
function set3D(enabled){document.querySelectorAll('[data-view],#reset-d,#section,#edges,#transparent,#dimensions,#ground,#tube,#explode,#snapshot,.montage-panel button,.montage-panel input,.montage-panel select').forEach(e=>e.disabled=!enabled);if(matchMedia('(prefers-reduced-motion: reduce)').matches)$('#montage-speed').disabled=true;}
set3D(false);
try{
 const host=$('#viewport'),renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe8eee9);host.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Variante D mit vollständig versenktem Schraubenkopf');
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.1,2000);camera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=12;controls.maxDistance=1000;
 scene.add(new THREE.HemisphereLight(0xffffff,0x60796b,2.7));const key=new THREE.DirectionalLight(0xfff6e9,3);key.position.set(120,-180,250);scene.add(key);const fill=new THREE.DirectionalLight(0xcce4ff,1.5);fill.position.set(-150,80,100);scene.add(fill);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(230,230),new THREE.MeshStandardMaterial({color:0xc9d8cb,roughness:1,side:THREE.FrontSide}));floor.position.z=-.03;scene.add(floor);
 const model=new THREE.Group();scene.add(model);let objects=[],thick=5,seq=0,guideShot=null;
 function geom(m){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(m.positions.flat(),3));g.setIndex(m.triangles.flat());g.computeVertexNormals();return g;}
 function edgegeom(m){const a=[];for(const e of m.edges)for(let i=1;i<e.length;i++)a.push(...e[i-1],...e[i]);return new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(a,3));}
 function update(){const section=$('#section').checked||(montage&&$('#montage-guide').checked&&progress>=2&&progress<4),ex=Number($('#explode').value);for(const o of objects){const cut=section&&!(montage&&o.id==='tube');o.mesh.geometry=cut?o.half:o.full;o.lines.geometry=cut?o.halfEdges:o.fullEdges;o.group.position.z=o.explode*ex;o.group.position.y=(o.explode_y||0)*ex;o.group.visible=o.visible&&(o.id!=='tube'||$('#tube').checked);o.lines.visible=$('#edges').checked;o.mesh.material.transparent=$('#transparent').checked;o.mesh.material.opacity=$('#transparent').checked?.28:1;o.mesh.material.depthWrite=!$('#transparent').checked;}if(montage){const pose=poseAt(progress,thick);const shot=$('#montage-guide').checked&&progress>=2&&progress<4?'thread':'whole';if(guideShot!==shot){guideShot=shot;frameMontage();}for(const o of objects){o.group.position.set(0,o.id==='pin'?pose.pinY:0,pose[o.id]);o.group.rotation.z=o.id==='tube'?pose.angle*Math.PI/180:o.id==='screw'&&!section?pose.screwAngle:0;} const i=stepAt(progress);$('#montage-title').textContent=`${i+1} / 8 · ${steps[i][0]}${Number.isInteger(progress)?' · Zielbild':' · Bewegung'}`;$('#montage-text').textContent=steps[i][1]+(progress>=6?' Kontakt unter Gewicht: Das Rohr steht hier mittig im 2-mm-Nutspiel; es würde bis zum Kontakt etwa 1 mm absinken. Nicht animiert, kein Lastnachweis.':'');$('#timeline').value=progress;document.querySelectorAll('[data-montage-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.montageStep)===i)));}else{objects.forEach(o=>o.group.rotation.z=0);}floor.visible=$('#ground').checked&&ex===0;$('#assembly-note').textContent=montage?'Montageerklärung auf unbestätigter CAD-Geometrie · keine Rastung, kein Belastungsnachweis.':ex>0?'Explosionsansicht: Teile bewusst verschoben; keine Betriebslage.':'Montagelage: Platte bei z = 0; Schraubenkopf 0,2 mm zurückgesetzt. Kein Teil ragt unter die Bodenebene.';}
 function view(kind){if(montage)return;if(kind==='detail'){$('#section').checked=true;$('#ground').checked=false;$('#explode').value='0';update();controls.target.set(0,0,thick+5);camera.position.set(25,-65,thick+15);}else if(kind==='bottom'){$('#ground').checked=false;update();controls.target.set(0,0,0);camera.position.set(30,-45,-240);}else{const tube=$('#tube').checked;controls.target.set(0,0,tube?75:22);if(kind==='side')camera.position.set(0,-310,22);else camera.position.set(195,-245,tube?245:180);if(host.clientWidth<500)camera.position.multiplyScalar(1.3);}controls.update();}
 const labels=[['150 mm',new THREE.Vector3(0,-77,0)],['150 mm',new THREE.Vector3(77,0,0)],['Ø24',new THREE.Vector3(-15,0,45)],['',new THREE.Vector3(-76,-72,3)]];for(const l of labels){l.push(document.createElement('span'));l[2].className='measure';$('#dimension-labels').append(l[2]);}
 function drawLabels(){const show=!montage&&$('#dimensions').checked&&Number($('#explode').value)===0;for(let i=0;i<labels.length;i++){const [t,p,el]=labels[i];const q=p.clone().project(camera);el.hidden=!show||q.z>1||q.z< -1;el.textContent=i===3?thick+' mm':t;el.style.left=(q.x+1)*host.clientWidth/2+'px';el.style.top=(1-q.y)*host.clientHeight/2+'px';}}
 async function load(){const n=++seq;thick=Number($('#thickness').value);$('#status').textContent='3D wird geladen …';model.visible=false;set3D(false);$('#checks').replaceChildren();delete document.body.dataset.ready;try{const r=await fetch(`assets/sockel-d/model-${thick}.json?rev=3`);if(!r.ok)throw Error('Modelldatei nicht erreichbar');const d=await r.json();if(n!==seq)return;if(d.revision!=='D-V03'||d.parts.map(p=>p.id).sort().join(',')!=='adapter,pin,plate,screw,tube')throw Error('Unerwartete Modellrevision oder Teileliste');objects.forEach(o=>{model.remove(o.group);o.full.dispose();o.half.dispose();o.fullEdges.dispose();o.halfEdges.dispose();o.mesh.material.dispose();o.lines.material.dispose();});objects=[];$('#parts').replaceChildren();for(const p of d.parts){const full=geom(p.full),half=geom(p.section),fullEdges=edgegeom(p.full),halfEdges=edgegeom(p.section);const mesh=new THREE.Mesh(full,new THREE.MeshStandardMaterial({color:p.color,metalness:.3,roughness:.4,side:THREE.DoubleSide}));const lines=new THREE.LineSegments(fullEdges,new THREE.LineBasicMaterial({color:0x344d46,transparent:true,opacity:.45}));const group=new THREE.Group();group.add(mesh,lines);model.add(group);const o={...p,group,mesh,lines,full,half,fullEdges,halfEdges,visible:true};objects.push(o);if(p.id!=='tube'){const l=document.createElement('label'),c=document.createElement('input'),sw=document.createElement('span');c.type='checkbox';c.checked=true;c.onchange=()=>{o.visible=c.checked;update();};sw.className='swatch';sw.style.background=p.color;l.append(c,sw,document.createTextNode(p.label));$('#parts').append(l);}}
 const c=d.checks;$('#checks').replaceChildren();for(const [k,v] of [['Unterstand','0 mm'],['Kopfrückstand','0,2 mm'],['Restdicke an Bohrung',c.remaining_plate_at_bore_mm+' mm'],['Nominaler Gewindeeingriff',c.nominal_engagement_mm+' mm'],['Abstand zum Bohrungsgrund',c.bore_end_clearance_mm+' mm'],['Körper / STEP',c.valid_solids+' gültig / geprüft'],['CAD-Einführlage','keine Volumenüberschneidung']]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;row.append(dt,dd);$('#checks').append(row);}
 model.visible=true;set3D(true);if(montage)lockMontage(true);
 $('#status').textContent='D-V03 · '+thick+' mm Platte';$('#error').hidden=true;update();if(montage){frameMontage();}else view('iso');document.body.dataset.ready=String(thick);
 }catch(e){if(n!==seq)return;model.visible=false;set3D(false);$('#error').hidden=false;$('#error').textContent='Modell nicht geladen: '+e.message;$('#status').textContent='Ladefehler';}}
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));for(const id of ['section','edges','transparent','dimensions','ground'])$('#'+id).onchange=update;$('#tube').onchange=()=>{update();view('iso');};$('#explode').oninput=update;document.addEventListener('platechange',()=>{pause();load();});$('#reset-d').onclick=()=>{leaveMontage();progress=0;$('#tube').checked=true;$('#section').checked=false;$('#transparent').checked=false;$('#explode').value='0';$('#ground').checked=true;$('#edges').checked=true;objects.forEach(o=>o.visible=true);$('#parts').querySelectorAll('input').forEach(c=>c.checked=true);update();view('iso');};

 function frameMontage(){if(guideShot==='thread'){controls.target.set(0,0,thick+48);camera.position.set(100,-155,thick+95);}else{controls.target.set(0,0,155);camera.position.set(420,520,390);}if(host.clientWidth<500)camera.position.sub(controls.target).multiplyScalar(1.2).add(controls.target);controls.update();}
 function pause(){playing=false;$('#play-montage').textContent='Abspielen';}
 function lockMontage(on){document.querySelectorAll('[data-view],#parts input,#tube,#explode,#dimensions').forEach(e=>e.disabled=on);document.body.classList.toggle('is-montage',on);}
 function enterMontage(){if(!montage){montage=true;guideShot=null;$('#explode').value=0;$('#tube').checked=true;objects.forEach(o=>o.visible=true);$('#parts').querySelectorAll('input').forEach(c=>c.checked=true);controls.target.set(0,0,155);camera.position.set(420,520,390);controls.update();}lockMontage(true);$('#montage-mode').textContent='Freie Ansicht';update();}
 function leaveMontage(){pause();montage=false;guideShot=null;lockMontage(false);$('#montage-mode').textContent='Montage ansehen';objects.forEach(o=>o.group.rotation.z=0);update();view('iso');}
 $('#montage-guide').onchange=()=>{guideShot=null;update();};
 $('#montage-mode').onclick=()=>{if(montage)leaveMontage();else enterMontage();};
 $('#play-montage').onclick=()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){pause();progress=Math.min(7,Math.floor(progress)+1);enterMontage();return;}enterMontage();if(playing){pause();return;}if(progress>=7)progress=0;playing=true;previousTime=null;$('#play-montage').textContent='Pause';update();};
 $('#timeline').oninput=()=>{pause();progress=Number($('#timeline').value);enterMontage();};
 $('#montage-back').onclick=()=>{pause();progress=Math.max(0,Math.ceil(progress)-1);enterMontage();};
 $('#montage-next').onclick=()=>{pause();progress=Math.min(7,Math.floor(progress)+1);enterMontage();};
 $('#montage-replay').onclick=()=>{pause();progress=0;enterMontage();};
 steps.forEach(([title],i)=>{const b=document.createElement('button');b.dataset.montageStep=i;b.textContent=`${i+1} · ${title}`;b.onclick=()=>{pause();progress=i;enterMontage();};$('#montage-steps').append(b);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
 if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('#play-montage').hidden=true;$('#montage-speed').disabled=true;}
 $('#montage-speed').value=matchMedia('(prefers-reduced-motion: reduce)').matches?'slow':'explain';
 $('#snapshot').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download=`Sockel-D-V03-${thick}mm.png`;a.href=renderer.domElement.toDataURL('image/png');a.click();};
 new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();if(montage)frameMontage();}).observe(host);renderer.setAnimationLoop(time=>{if(playing){const dt=previousTime===null?0:Math.min((time-previousTime)/1000,.1);progress=Math.min(7,progress+dt/($('#montage-speed').value==='demo'?2:$('#montage-speed').value==='slow'?8:5));update();if(progress>=7)pause();}previousTime=time;controls.update();drawLabels();renderer.render(scene,camera);});await load();
}catch(e){set3D(false);$('#status').textContent='3D nicht verfügbar · Dokumente nutzbar';$('#error').hidden=false;$('#error').textContent='3D-Ansicht nicht verfügbar. Plattenwahl, Zeichnungen und Downloads bleiben nutzbar. '+e.message;}
