const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const initial=new URL(location.href), allowed=[5,8,9];
let state={plate:allowed.includes(+initial.searchParams.get('plate'))?+initial.searchParams.get('plate'):5,route:['model','build','project'].includes(initial.searchParams.get('view'))?initial.searchParams.get('view'):'model',step:Math.max(0,Math.min(7,Number(initial.searchParams.get('step'))||0)),view:'assembly',project:'parts'};
let timer=null,viewer=null,threeBusy=false,transparency=false;const scrollPositions={model:0,build:0,project:0};
const steps=[
 ['Teile vorbereiten','Die Platte anheben und die fünf Bauteile bereitlegen.','Die angehobene Platte ist schematisch dargestellt. 35 mm sind keine geprüfte Werkzeugfreiheit. Sichere Auflagen und Zugang von unten müssen am Muster geprüft werden.'],
 ['Querstift einsetzen','Der Stift wird radial in die massive Aufnahme eingesetzt.','Fertigungsschritt: Sitz, Passung und Sicherung sind offen. Bloßes Einstecken ist keine nachgewiesene Stiftsicherung. Vor der Benutzermontage muss der Stift gesichert sein.'],
 ['Aufnahme aufsetzen','Die massive Aufnahme steht auf der sauberen Oberseite der Platte.','Das Gewindesackloch liegt direkt im Vollmaterial. Kontaktflächen und Beschichtung müssen zur späteren Vorspannung passen.'],
 ['Von unten verschrauben','Die Senkschraube verbindet Platte und massive Aufnahme.','Aufnahme gegen Mitdrehen halten. Reale Kopfkontur, tragende Gewindelänge und Anziehverfahren sind noch festzulegen. Schnitt erklärt den Gewindesitz; kein Gewindeflanken- oder Kraftnachweis.'],
 ['Sockel absetzen','Die Platte wird auf die ebene Prüffläche gestellt.','Im nominalen CAD liegt der Schraubenkopf 0,2 mm oberhalb der Bodenebene. Am realen, beschichteten Teil mit Richtkante prüfen.'],
 ['Schlitz ausrichten','Den offenen Rohrschlitz zum radialen Stift ausrichten.','Das Rohr steht im Modell 40 mm über seiner Einführlage. Reale Ausrichtung und Passung müssen am Original bestätigt werden.'],
 ['Rohr aufschieben','Das Rohr axial absenken, bis der Stift den seitlichen Nutabschnitt erreicht.','Ohne Verkanten und ohne erzwungene Verdrehung einführen. Bei Klemmen stoppen. Radialspiel und Schlitzspiel sind nominale Konzeptwerte.'],
 ['Rohr verdrehen','Von oben betrachtet um 50° gegen den Uhrzeigersinn drehen.','50° ist eine Demonstrationsposition vor dem nominalen Anschlag bei etwa 55,8°. Keine Rastung. Rückdrehen bleibt frei. Das Rohr steht mittig im Nutspiel; Kontakt unter Gewicht und Losdrehen der Sockelaufnahme sind nicht simuliert.']
];
const parts=[
 {name:'Grundplatte',dimension:()=>`150 × 150 × ${state.plate} mm`,cad:'Mittige Bohrung und idealisierte 90°-Senkung.',candidate:'S235-Platte. Bepreister Kandidat bisher nur für 5 mm.',decision:'Ebenheit, Material, Beschichtung und Senkung zum realen Schraubenkopf festlegen.',id:'plate'},
 {name:'Massive Aufnahme',dimension:()=> 'Ø24 × 50 mm · direktes M8-Sackloch',cad:'Vollmaterial; Gewinde-Zieltiefe 18 mm. Werkstoff noch offen.',candidate:'Ø25-Vollstahl auf Ø24 bearbeiten.',decision:'Werkstoff, wirksame Gewindelänge, Oberfläche und Stiftsitz auslegen.',id:'adapter'},
 {name:'Querstift',dimension:()=> 'Ø4 × 21 mm · 17 mm Überstand',cad:'Separater Stift mit konzeptionell 4 mm Sitz.',candidate:'Normstift Ø4 × 20 mm: nicht identisch mit dem CAD.',decision:'Sitz, Überstand, Sicherung und Materialangabe klären.',id:'pin'},
 {name:'Senkschraube',dimension:()=> 'M8 × 20 · idealisierte Kopfhülle',cad:'Nominal 0,2 mm über der Bodenebene; kein verifiziertes Kaufteil.',candidate:'Konkrete Norm-Senkschraube mit Datenblatt auswählen.',decision:'Kopfkontur, Festigkeitsklasse und Anziehverfahren prüfen.',id:'screw'},
 {name:'Fackelrohr',dimension:()=> 'Ø27 / innen Ø25 × 180 mm',cad:'Geschlitztes Rohr aus unbestätigtem Fotoentwurf.',candidate:'Rohr Ø28 × 1,5 mm: andere Wandstärke und Außengeometrie.',decision:'Innenmaß, Naht, Ovalität, Schlitz und oberen Anschluss prüfen.',id:'tube'}
];
function url(push=false){const u=new URL(location.href);u.searchParams.set('plate',state.plate);u.searchParams.set('view',state.route);if(state.route==='build')u.searchParams.set('step',state.step);else u.searchParams.delete('step');history[push?'pushState':'replaceState'](null,'',u);}
function pause(){if(timer)clearInterval(timer);timer=null;$('#step-play').textContent='Abspielen';$('#step-state').textContent='Schrittfolge mit CAD-Zielbildern. Jederzeit pausierbar.';}
function closeDialogs(){$$('dialog[open]').forEach(d=>d.close());}
function route(name,push=true){pause();if(viewer)exit3d();closeDialogs();scrollPositions[state.route]=scrollY;state.route=name;for(const r of ['model','build','project'])$(`#${r}-view`).hidden=r!==name;$$('.app-nav button').forEach(b=>{if(b.dataset.route===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});url(push);window.scrollTo({top:scrollPositions[name],behavior:'instant'});$('#content').focus({preventScroll:true});}
function imagePath(){return `assets/ux/${state.view}-${state.plate}.png`;}
function showModel(){const src=imagePath();$('#model-image').src=src;$('#model-image').alt=`D-V03, ${state.plate}-mm-Platte, ${state.view==='assembly'?'Gesamtansicht':state.view==='section'?'CAD-Schnitt':'Explosionsansicht'}`;$('#image-download').href=src;$$('[data-model-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.modelView===state.view)));if(viewer)viewer.setView(state.view);}
function showStep(){const i=state.step;$('#build-image').src=`assets/ux/step-${i}-${state.plate}.png`;$('#build-image').alt=`CAD-Zielbild ${i+1}: ${steps[i][0]}, ${state.plate}-mm-Platte`;$('#step-count').textContent=`${String(i+1).padStart(2,'0')} / 08`;$('#step-heading').textContent=steps[i][0];$('#step-text').textContent=steps[i][1];$('#step-detail').textContent=steps[i][2];$('#step-prev').disabled=i===0;$('#step-next').disabled=i===7;$$('[data-step]').forEach(b=>{if(+b.dataset.step===i)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});if(i<7){const img=new Image();img.src=`assets/ux/step-${i+1}-${state.plate}.png`;}url();}
function renderParts(){const openIds=$$('.bom-item[open]').map(e=>e.dataset.part);$('#bom').innerHTML=parts.map((p,i)=>`<details class="bom-item" data-part="${p.id}" ${openIds.includes(p.id)?'open':''}><summary><span class="part-number">0${i+1}</span><span class="part-name">${p.name}<span class="part-dimension">${p.dimension()}</span></span><span class="part-plus" aria-hidden="true">＋</span></summary><div class="part-details"><dl><dt>Aktuelles CAD</dt><dd>${p.cad}</dd><dt>Recherchekandidat</dt><dd>${p.candidate}</dd><dt>Vor Übernahme entscheiden</dt><dd>${p.decision}</dd></dl><p class="part-status">Konzept · nicht fertigungsfreigegeben</p><a class="text-link" href="assets/sockel-d/${p.id}-${state.plate}.step">Einzelteil als STEP ↓</a></div></details>`).join('');}
function costs(){const q=+$('#quantity').value;const prices={1:['90–230','230–830'],5:['130–270','460–1.730'],10:['190–330','800–3.030']};$('#diy-price').textContent=`ca. ${prices[q][0]} €`;$('#shop-price').textContent=`ca. ${prices[q][1]} €`;$('#cost-context').textContent=`${state.plate===5?'Auch für die gewählte 5-mm-Ausführung fehlt ein vollständiger CAD-Stücklistenpreis.':`Für die gewählte ${state.plate}-mm-Ausführung fehlt eine Gesamtkalkulation.`} Die angezeigte Studie gilt nur für eine 5-mm-Platte mit abweichendem Rohr und Stift.`;}
function drawing(){const src=`assets/sockel-d/blatt-${state.plate}-${$('#drawing-sheet').value}.png?rev=5`;$('#drawing-image').src=src;$('#drawing-image').alt=`Prüfzeichnung D-V03, ${state.plate} mm, Blatt ${$('#drawing-sheet').value}`;$('#drawing-large').href=src;}
async function plate(t){pause();state.plate=t;$$('[data-plate-label]').forEach(e=>e.textContent=`${t} mm`);$$('[data-plate]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.plate===t)));$$('[data-document]').forEach(a=>a.href=`${a.dataset.document}.html?plate=${t}`);for(const id of ['assembly-download','step-download'])$('#'+id).href=`assets/sockel-d/assembly-${t}.step`;$('#pdf-download').href=`assets/sockel-d/zeichnungen-D-V03-${t}mm.pdf`;showModel();showStep();renderParts();costs();drawing();url();if(viewer&&!$('#interactive-stage').hidden){exit3d();await activate3d();}}
async function activate3d(){if(threeBusy)return;threeBusy=true;$('#activate-3d').disabled=true;$('#interaction-note').textContent='3D wird vorbereitet …';try{const {createViewer}=await import('./ux-viewer.js?rev=1');if(!viewer)viewer=await createViewer($('#interactive-stage'),state.plate);else await viewer.load(state.plate);viewer.setView(state.view);viewer.setTransparent(transparency);$('#interactive-stage').hidden=false;$('#model-image').hidden=true;$('#activate-3d').hidden=true;$('#exit-3d').hidden=false;$('#rotation-tools').hidden=false;$('#stage-tag').textContent='3D aktiv';$('#interaction-note').textContent='Ziehen: drehen. Zwei Finger: zoomen. „3D beenden“ gibt die Fläche zum Scrollen frei.';viewer.start();}catch(e){$('#interactive-stage').hidden=true;$('#model-image').hidden=false;$('#interaction-note').textContent='3D ist hier nicht verfügbar. Gesamtansicht, Schnitt und Zerlegung bleiben als CAD-Bilder nutzbar.';$('#activate-3d').textContent='3D erneut versuchen';console.warn('UX preview WebGL unavailable:',e.message);}finally{threeBusy=false;$('#activate-3d').disabled=false;}}
function exit3d(){if(viewer)viewer.stop();$('#interactive-stage').hidden=true;$('#model-image').hidden=false;$('#activate-3d').hidden=false;$('#exit-3d').hidden=true;$('#rotation-tools').hidden=true;$('#stage-tag').textContent='CAD-Ansicht';$('#interaction-note').textContent='Die Seite bleibt scrollbar. 3D startet erst auf Wunsch.';}
$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));$$('[data-open]').forEach(b=>b.onclick=()=>{pause();$('#'+b.dataset.open).showModal();});$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$$('[data-plate]').forEach(b=>b.onclick=()=>{closeDialogs();plate(+b.dataset.plate);});$$('[data-model-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.modelView;showModel();});$$('[data-inspect]').forEach(b=>b.onclick=()=>{state.view=b.dataset.inspect;closeDialogs();showModel();});$('#activate-3d').onclick=activate3d;$('#exit-3d').onclick=exit3d;$$('[data-turn]').forEach(b=>b.onclick=()=>viewer?.turn(+b.dataset.turn));$$('[data-zoom]').forEach(b=>b.onclick=()=>viewer?.zoom(+b.dataset.zoom));$('#reset-camera').onclick=()=>viewer?.reset();$('#transparent-toggle').onclick=async()=>{closeDialogs();transparency=!transparency;await activate3d();};
$('#step-prev').onclick=()=>{pause();state.step=Math.max(0,state.step-1);showStep();};$('#step-next').onclick=()=>{pause();state.step=Math.min(7,state.step+1);showStep();};$('#restart').onclick=()=>{pause();state.step=0;showStep();};$('#step-play').onclick=()=>{if(timer){pause();return;}if(state.step===7){state.step=0;showStep();}$('#step-play').textContent='Pause';$('#step-state').textContent='Bildfolge läuft · ein Schritt alle 5 Sekunden';timer=setInterval(()=>{state.step++;showStep();if(state.step===7)pause();},5000);};
steps.forEach(([title],i)=>{const b=document.createElement('button');b.dataset.step=i;b.textContent=`${String(i+1).padStart(2,'0')}  ${title}`;b.onclick=()=>{pause();state.step=i;showStep();closeDialogs();};$('#step-list').append(b);});
$$('[data-project]').forEach(b=>b.onclick=()=>{state.project=b.dataset.project;$$('[data-project]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));for(const p of ['parts','checks','costs'])$('#'+p+'-panel').hidden=p!==state.project;});$('#quantity').onchange=costs;$('#drawing-sheet').onchange=drawing;
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();exit3d();}});window.addEventListener('popstate',()=>{const u=new URL(location.href);state.step=Math.max(0,Math.min(7,+u.searchParams.get('step')||0));plate(allowed.includes(+u.searchParams.get('plate'))?+u.searchParams.get('plate'):5);route(['model','build','project'].includes(u.searchParams.get('view'))?u.searchParams.get('view'):'model',false);});
if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('#step-play').hidden=true;$('.step-controls').classList.add('manual');$('#step-state').textContent='Reduzierte Bewegung: Schritte manuell auswählen.';}
await plate(state.plate);route(state.route,false);document.body.dataset.ready='true';
