import * as THREE from 'three';
import {OrbitControls} from 'three/addons/OrbitControls.js';
const $=s=>document.querySelector(s);
const data={
A:{name:'Original kürzen',hours:[.75,1.5],material:[15,35],principle:'Der Erdspieß wird gekürzt. Ein axiales Innengewinde nimmt die Schraube durch die Platte auf. Nur sinnvoll, wenn das Original massiv und gut bearbeitbar ist.',load:'Schraube → Innengewinde → gekürzter Schaft. Die Schraubenvorspannung presst die kleine Stirnfläche auf die Platte; Reibung hält gegen Verdrehen.',effort:'Absägen, plan bearbeiten, zentrisch bohren und Gewinde schneiden; Platte durchbohren; Schraubenkopf liegt unter der Platte.',weak:'Kleine Auflage und geschwächter Schaftquerschnitt durch die Bohrung. Ohne Zusatzsicherung kann sich die Aufnahme beim Drehen lösen.',stability:'Am stärksten vom Original abhängig; schmale Auflage, keine formschlüssige Verdrehsicherung.',driver:'Original spannen, Material prüfen, Bohrung zentrieren'},
B:{name:'Breiter Fuß + Passstift',hours:[1.5,3],material:[30,60],principle:'Ein neuer Adapter erhält einen breiten Fuß. Eine zentrale Schraube spannt ihn auf die Platte, ein exzentrischer Passstift verhindert Mitdrehen.',load:'Schraube → Innengewinde → Fußauflage → Platte. Der Passstift überträgt Drehmoment zusätzlich zur Reibung; er ersetzt nicht die Vorspannung.',effort:'Drehteil fertigen, Gewinde schneiden, seitlichen Stift setzen und zwei zueinander passende Passstiftbohrungen herstellen.',weak:'Schmaler Hals bleibt mögliche Biegestelle. Passstift und Platte müssen passend ausgelegt werden; kein Lastnachweis.',stability:'Guter Kompromiss: breite Auflage, gezielte Verdrehsicherung; Hals bleibt zu prüfen.',driver:'Neues Drehteil und genaue Passstiftposition'},
C:{name:'Flansch mit drei Schrauben',hours:[2,4],material:[40,80],principle:'Drei Schrauben von unten greifen in den verbreiterten Flansch. Die Befestigungspunkte sind über einen Lochkreis verteilt.',load:'Flanschkontakt und räumlich getrennte Schrauben übertragen das Moment auf die Platte. Drehbewegung wird durch Schraubenanordnung und Klemmung begrenzt.',effort:'Flanschadapter drehen, drei Gewinde und deckungsgleiche Plattenbohrungen setzen; Schraubenköpfe unter der Platte.',weak:'Platte kann lokal nachgeben; Flansch, kurze Gewindeeingriffe und Hals müssen bemessen werden. Mehr Schrauben allein sind kein Festigkeitsnachweis.',stability:'Günstigste Befestigungsanordnung der vier Konzepte; keine quantitative Belastbarkeitszusage.',driver:'Lochkreis und mehrere Gewinde / Senkungen'},
D:{name:'Hülse mit Gewindebuchse',hours:[2,4],material:[30,70],principle:'Eine Hülse erhält unten eine separate Gewindebuchse. Im dargestellten Konzept ist sie umlaufend gefügt; die orange Zone markiert die noch auszulegende Verbindung.',load:'Schraube → Gewindebuchse → Fügezone → Hülse/Kopf. Der Einsatz muss axial und gegen Verdrehen gehalten werden. Eine lose Mutter würde diese Aufgabe nicht erfüllen.',effort:'Hülse und Buchse fertigen, ausrichten, fügen, nacharbeiten und Fügezone prüfen. Keine Schweißbarkeit des Originals vorausgesetzt.',weak:'Zusätzliche kritische Schnittstelle: Qualität und Dimension der Fügezone. Wärmeeintrag kann verziehen; Material muss zum Verfahren passen.',stability:'Bei fachgerechter Auslegung möglich; größte zusätzliche Unsicherheit durch den Einsatz.',driver:'Buchse fügen, Verzug und Fügequalität beherrschen'}
};
function budget(d){return [Math.round((d.hours[0]*80+d.material[0])*1.19),Math.round((d.hours[1]*120+d.material[1])*1.19)];}
for(const [id,d] of Object.entries(data)){const row=document.createElement('tr');for(const t of [id+' · '+d.name,d.hours.join('–')+' h',budget(d).join('–')+' €',d.stability,d.driver]){const c=document.createElement('td');c.textContent=t;row.append(c);}$('#comparison').append(row);}
try{
const host=$('#viewport'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe9eef4);host.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Drehbare Sockelvariante');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,2000);camera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=30;controls.maxDistance=1000;
scene.add(new THREE.HemisphereLight(0xffffff,0x7f8b9c,2.6));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(100,-160,220);scene.add(light);
const group=new THREE.Group();scene.add(group);let objects=[],current='B',token=0;
function fit(kind='iso'){const z=$('#v-tube').checked?90:35;controls.target.set(0,0,z);if(kind==='under')camera.position.set(120,-180,-170);else if(kind==='close'){controls.target.set(0,0,19);camera.position.set(75,-100,65);}else camera.position.set(190,-240,$('#v-tube').checked?220:170);if(host.clientWidth<500&&kind==='iso')camera.position.multiplyScalar(1.3);controls.update();}
function update(){const section=$('#v-section').checked,ex=Number($('#v-explode').value);for(const o of objects){o.mesh.geometry=section?o.cut:o.full;o.mesh.visible=o.visible&&(o.kind!=='tube'||$('#v-tube').checked)&&!!o.mesh.geometry;o.mesh.position.z=o.explode*ex;}}
function geometry(m){if(!m)return null;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(m.positions.flat(),3));g.setIndex(m.triangles.flat());g.computeVertexNormals();return g;}
async function load(id){const request=++token;$('#vstatus').textContent='Laden …';try{const r=await fetch(`assets/variants/${id}.json`);if(!r.ok)throw Error('Modelldatei nicht erreichbar');const m=await r.json();if(request!==token)return;objects.forEach(o=>{group.remove(o.mesh);o.full.dispose();o.cut?.dispose();o.mesh.material.dispose();});objects=[];$('#parts').replaceChildren();current=id;for(const p of m.parts){const full=geometry(p.full),cut=geometry(p.section),material=new THREE.MeshStandardMaterial({color:p.color,metalness:.2,roughness:.5,side:THREE.DoubleSide});const mesh=new THREE.Mesh(full,material);group.add(mesh);const o={...p,full,cut,mesh,visible:true};objects.push(o);const label=document.createElement('label'),check=document.createElement('input'),swatch=document.createElement('span');check.type='checkbox';check.checked=true;check.onchange=()=>{o.visible=check.checked;update();};swatch.className='swatch';swatch.style.background=p.color;label.append(check,swatch,document.createTextNode(p.label));if(p.kind!=='tube')$('#parts').append(label);}
const d=data[id];$('#variant-title').textContent='Variante '+id;for(const k of ['name','principle','load','effort','weak'])$('#'+k).textContent=d[k];$('#cost').textContent=budget(d).join('–')+' €';$('#hours').textContent=d.hours.join('–')+' h Werkstattzeit · '+d.material.join('–')+' € Material/Kleinteile netto';$('#calculation').textContent='Rechenweg: (Zeit × 80–120 €/h + Material) × 1,19. Eigene Schätzung; kein Angebot.';$('#step').href=`assets/variants/${id}-concept.step`;document.querySelectorAll('[data-variant]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.variant===id)));$('#vstatus').textContent='V01 · '+m.parts.length+' CAD-Teile';$('#error').hidden=true;update();fit();document.body.dataset.variant=id;
}catch(e){$('#error').hidden=false;$('#error').textContent=e.message;$('#vstatus').textContent='Laden fehlgeschlagen';}}
for(const b of document.querySelectorAll('[data-variant]'))b.onclick=()=>load(b.dataset.variant);
$('#v-section').onchange=update;$('#v-explode').oninput=update;$('#v-tube').onchange=()=>{update();fit();};$('#v-iso').onclick=()=>fit();$('#v-under').onclick=()=>fit('under');$('#v-close').onclick=()=>fit('close');
new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe(host);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});await load('B');
}catch(e){$('#error').hidden=false;$('#error').textContent='3D nicht verfügbar: '+e.message;}
