import * as THREE from './vendor/three.module.js';
import {mountPrinciple} from './xray-principle.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {parts,steps,buildParts,applyPose,activeStep,cameraPose,vectorScene} from './xray-model.js?rev=3';
const $=s=>document.querySelector(s),host=$('#xr-viewport'),entry=new URL(location.href),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const number=(key,fallback,min,max)=>{const n=Number(entry.searchParams.get(key));return entry.searchParams.has(key)&&Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;};
const state={mode:entry.searchParams.get('mode')==='montage'?'montage':'assembly',progress:number('step',parts.length,0,parts.length),explode:number('explode',0,0,1),selected:parts.some(p=>p.id===entry.searchParams.get('part'))?entry.searchParams.get('part'):'',hidden:(entry.searchParams.get('hidden')||'').split(',').filter(id=>parts.some(p=>p.id===id)),cut:entry.searchParams.get('cut')==='1',transparent:entry.searchParams.get('transparent')==='1',solo:entry.searchParams.get('solo')==='1',dimensions:entry.searchParams.get('dimensions')==='1'};
const scene=new THREE.Scene();scene.background=new THREE.Color('#edf2f5');const camera=new THREE.PerspectiveCamera(38,1,1,6000);camera.position.set(...cameraPose());const target=new THREE.Vector3(0,0,0);camera.lookAt(target);const objects=buildParts();objects.forEach(o=>scene.add(o.group));
scene.add(new THREE.HemisphereLight(0xddeeff,0x4c4850,2.6));for(const [p,i] of [[[300,600,450],3],[[-400,100,-300],1.8]]){const light=new THREE.DirectionalLight(0xffffff,i);light.position.set(...p);scene.add(light);}
const plane=new THREE.Plane(new THREE.Vector3(0,0,-1),0);let renderer=null,controls=null,playing=false,interacting=false,previous=0,dirty=true,lastVector=0;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer:coarse)').matches?1.5:2));renderer.localClippingEnabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.querySelector('img').remove();host.prepend(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(target);controls.enableDamping=true;controls.enabled=false;controls.minDistance=160;controls.maxDistance=2200;controls.addEventListener('change',()=>dirty=true);$('#xr-status').textContent='Interaktives 3D · fiktives Modell';$('#xr-render-note').textContent='Drehen und Zoomen bewusst aktivieren. Antippen wählt ein Bauteil; die Liste funktioniert auch ohne präzisen Treffer.';}catch{renderer?.dispose();renderer=null;host.querySelector('img').remove();const surface=document.createElement('div');surface.id='xr-vector';host.prepend(surface);$('#xr-status').textContent='Interaktive Vektoransicht · ohne WebGL';$('#xr-render-note').textContent='WebGL ist hier nicht verfügbar. Diese Ersatzansicht projiziert dieselben Modellnetze: Auswahl, Schritte, Schnitt und Drehen bleiben nutzbar; Überdeckungen und Transparenz sind vereinfacht.';}
const dimensionLabel=document.createElement('div');dimensionLabel.id='xr-dimension-label';dimensionLabel.textContent='Gesamt ca. 470 × 238 × 246 Demo-mm · frei erfunden';dimensionLabel.hidden=true;host.append(dimensionLabel);
function size(){const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.zoom=Math.min(1,camera.aspect/1.4);camera.updateProjectionMatrix();renderer?.setSize(w,h);dirty=true;}
new ResizeObserver(size).observe(host);size();
function frame(view='iso',wide=false){const pos=cameraPose(view);camera.position.set(...pos).multiplyScalar(wide?1.65:1);target.set(0,wide?30:0,0);camera.lookAt(target);if(controls){controls.target.copy(target);controls.update();}dirty=true;}
for(const [key,vec] of [['camera',camera.position],['target',target]]){const a=(entry.searchParams.get(key)||'').split(',').map(Number);if(a.length===3&&a.every(x=>Number.isFinite(x)&&Math.abs(x)<=3000))vec.set(...a);}camera.lookAt(target);if(controls){controls.target.copy(target);controls.update();}
function pause(){playing=false;previous=0;$('#xr-play').textContent=reduced?'Reduzierte Bewegung · Schritte nutzen':'Montage abspielen';}
function update(){
 dimensionLabel.hidden=!state.dimensions;
 applyPose(objects,state);objects.forEach(o=>o.meshes.forEach(m=>m.material.clippingPlanes=state.cut?[plane]:null));
 $('#xr-part').value=state.selected;$('#xr-explode').value=state.explode;$('#xr-timeline').value=state.progress;for(const k of ['solo','transparent','cut','dimensions'])$('#xr-'+k).checked=state[k];$('#xr-solo').disabled=!state.selected;
 document.querySelectorAll('[data-xr-visible]').forEach(e=>e.checked=!state.hidden.includes(e.dataset.xrVisible));const part=parts.find(p=>p.id===state.selected);$('#xr-part-info').hidden=!part;
 if(part){$('#xr-part-name').textContent=part.name;$('#xr-part-detail').textContent=`${part.size} Demo-mm · ${part.material}. ${part.task}`;$('#xr-record').href='#part-'+part.id;$('#xr-source').href='#source-'+part.id;$('#xr-part-stl').href=`assets/xray-demo/${part.id}.stl`;}
 const i=activeStep(state.progress);$('#xr-step-count').textContent=`${i} / ${parts.length}`;$('#xr-step-title').textContent=state.mode==='montage'?`${String(i).padStart(2,'0')} · ${steps[i].name}${Number.isInteger(state.progress)?' · Zielbild':' · Bewegung'}`:'Gesamtanordnung';$('#xr-step-text').textContent=state.mode==='montage'?steps[i].text:'Fiktives Anschauungsmodell. Bauteil wählen, Gehäuse transparent stellen oder die schrittweise Erklärmontage starten.';
 document.querySelectorAll('[data-xr-step]').forEach(b=>b.setAttribute('aria-pressed',String(state.mode==='montage'&&Number(b.dataset.xrStep)===i)));dirty=true;
}
function select(id){pause();state.selected=id;if(!id)state.solo=false;update();}
function step(n){pause();state.mode='montage';state.progress=Math.max(0,Math.min(parts.length,n));state.solo=false;state.hidden=[];state.selected=state.progress?parts[activeStep(state.progress)-1].id:'';state.explode=0;frame('iso',true);update();}
$('#xr-part').onchange=e=>select(e.target.value);$('#xr-install').onclick=()=>step(parts.findIndex(p=>p.id===state.selected)+1);
$('#xr-focus').onclick=()=>{const o=objects.find(o=>o.id===state.selected);if(!o)return;pause();state.hidden=state.hidden.filter(id=>id!==o.id);update();const b=new THREE.Box3().setFromObject(o.group),center=b.getCenter(new THREE.Vector3()),d=Math.max(170,b.getSize(new THREE.Vector3()).length()*1.45);target.copy(center);camera.position.copy(center).add(new THREE.Vector3(.7,.45,.8).normalize().multiplyScalar(d));camera.lookAt(target);if(controls){controls.target.copy(target);controls.update();}dirty=true;};
for(const k of ['solo','transparent','cut','dimensions'])$('#xr-'+k).onchange=e=>{state[k]=e.target.checked;update();};
document.querySelectorAll('[data-xr-visible]').forEach(e=>e.onchange=()=>{state.hidden=state.hidden.filter(id=>id!==e.dataset.xrVisible);if(!e.checked)state.hidden.push(e.dataset.xrVisible);update();});
$('#xr-explode').oninput=e=>{pause();state.mode='assembly';state.explode=Number(e.target.value);frame('iso',state.explode>.1);update();};
$('#xr-timeline').oninput=e=>step(Number(e.target.value));$('#xr-prev').onclick=()=>step(Math.ceil(state.progress)-1);$('#xr-next').onclick=()=>step(Math.floor(state.progress)+1);$('#xr-restart').onclick=()=>step(0);
document.querySelectorAll('[data-xr-step]').forEach(b=>b.onclick=()=>step(Number(b.dataset.xrStep)));
$('#xr-play').disabled=reduced;$('#xr-play').onclick=()=>{if(playing){pause();return;}if(state.mode!=='montage'||state.progress>=parts.length)step(0);playing=true;previous=0;$('#xr-play').textContent='Pause';};
document.querySelectorAll('[data-xr-select]').forEach(b=>b.onclick=()=>{select(b.dataset.xrSelect);document.getElementById('model').scrollIntoView({behavior:reduced?'instant':'smooth'});});
document.querySelectorAll('[data-xr-view]').forEach(b=>b.onclick=()=>frame(b.dataset.xrView,state.mode==='montage'||state.explode>.1));
$('#xr-reset').onclick=()=>{pause();Object.assign(state,{mode:'assembly',progress:parts.length,explode:0,selected:'',hidden:[],cut:false,transparent:false,solo:false,dimensions:false});frame();update();};
$('#xr-interact').onclick=()=>{interacting=!interacting;host.classList.toggle('interacting',interacting);$('#xr-interact').setAttribute('aria-pressed',String(interacting));$('#xr-interact').textContent=interacting?'Seite wieder scrollen':'Drehen / Zoomen aktivieren';if(controls)controls.enabled=interacting;};
let down=null;const ray=new THREE.Raycaster();host.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;down={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY};if(!renderer&&interacting)host.setPointerCapture(e.pointerId);});
host.addEventListener('pointermove',e=>{if(renderer||!interacting||!down)return;const delta=camera.position.clone().sub(target),spherical=new THREE.Spherical().setFromVector3(delta);spherical.theta-=(e.clientX-down.lastX)*.007;spherical.phi=Math.max(.08,Math.min(Math.PI-.08,spherical.phi+(e.clientY-down.lastY)*.007));camera.position.copy(target).add(new THREE.Vector3().setFromSpherical(spherical));camera.lookAt(target);down.lastX=e.clientX;down.lastY=e.clientY;dirty=true;});
host.addEventListener('pointercancel',()=>down=null);host.addEventListener('pointerup',e=>{if(!down)return;const d=down;down=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>6)return;const r=host.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObjects(objects.filter(o=>o.group.visible).flatMap(o=>o.meshes));const hit=hits.find(h=>!state.cut||h.point.z<=.001);if(hit)select(hit.object.userData.partId);});
host.addEventListener('wheel',e=>{if(renderer||!interacting)return;e.preventDefault();const delta=camera.position.clone().sub(target),length=Math.max(160,Math.min(2200,delta.length()*Math.exp(e.deltaY*.001)));camera.position.copy(target).add(delta.setLength(length));camera.lookAt(target);dirty=true;},{passive:false});
function svg(){return vectorScene(objects,camera,host.clientWidth,host.clientHeight,{...state,dimensions:false});}
function render(){camera.updateMatrixWorld();if(renderer)renderer.render(scene,camera);else $('#xr-vector').innerHTML=svg();const o=objects.find(o=>o.id===state.selected),label=$('#xr-label');label.hidden=!o||!o.group.visible;if(o&&o.group.visible){const c=new THREE.Box3().setFromObject(o.group).getCenter(new THREE.Vector3()).project(camera);label.textContent=o.name;label.style.left=Math.max(10,Math.min(host.clientWidth-190,(c.x+1)*host.clientWidth/2))+'px';label.style.top=Math.max(12,Math.min(host.clientHeight-40,(1-c.y)*host.clientHeight/2))+'px';}host.dataset.rendered='true';}
$('#xr-share').onclick=async()=>{pause();const u=new URL(location.href);u.search='';u.hash='model';for(const k of ['mode','progress','explode','selected','cut','transparent','solo','dimensions'])u.searchParams.set(k==='progress'?'step':k==='selected'?'part':k,typeof state[k]==='boolean'?state[k]?'1':'0':String(state[k]));u.searchParams.set('hidden',state.hidden.join(','));u.searchParams.set('camera',camera.position.toArray().map(x=>x.toFixed(2)).join(','));u.searchParams.set('target',(controls?controls.target:target).toArray().map(x=>x.toFixed(2)).join(','));$('#xr-share-result').hidden=false;$('#xr-link').value=u.href;try{await navigator.clipboard.writeText(u.href);$('#xr-share-status').textContent='Ansichtslink kopiert.';}catch{$('#xr-link').focus();$('#xr-link').select();$('#xr-share-status').textContent='Link zum Kopieren ausgewählt.';}};
$('#xr-png').onclick=async()=>{pause();render();const out=document.createElement('canvas');out.width=1200;out.height=Math.round(1200*host.clientHeight/host.clientWidth)+80;const ctx=out.getContext('2d');try{if(renderer)ctx.drawImage(renderer.domElement,0,0,1200,out.height-80);else{const blob=new Blob([svg()],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();try{await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url;});ctx.drawImage(img,0,0,1200,out.height-80);}finally{URL.revokeObjectURL(url);}}ctx.fillStyle='#172c3e';ctx.fillRect(0,out.height-80,1200,80);ctx.fillStyle='#fff';ctx.font='20px sans-serif';ctx.fillText('XR-DEMO / 01 · FIKTIV · NICHT FUNKTIONSFÄHIG · KEINE FERTIGUNGSFREIGABE',24,out.height-46);ctx.font='16px sans-serif';ctx.fillText(`Ansicht: ${state.mode} · Schritt ${state.progress.toFixed(2)} / ${parts.length} · alle Maße erfunden`,24,out.height-18);const a=document.createElement('a');a.download='XR-DEMO-Ansicht.png';a.href=out.toDataURL('image/png');a.click();}catch{$('#xr-render-note').textContent='PNG-Export war in diesem Browser nicht möglich. Die SVG-Schemablätter unten bleiben verfügbar.';}};
document.querySelectorAll('.table-scroll table').forEach(table=>{const labels=[...table.querySelectorAll('th')].map(e=>e.textContent);table.querySelectorAll('tr').forEach(row=>row.querySelectorAll('td').forEach((td,i)=>td.dataset.label=labels[i]||''));});
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)document.querySelectorAll('[data-xr-nav]').forEach(a=>{if(a.getAttribute('href')==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-10% 0px -60% 0px'});document.querySelectorAll('main>section').forEach(e=>observer.observe(e));
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});pause();if(state.mode==='montage'&&!entry.searchParams.has('camera'))frame('iso',true);update();render();
const principle=mountPrinciple(id=>{pause();state.mode='assembly';state.progress=parts.length;state.explode=0;state.hidden=[];state.solo=false;state.transparent=true;frame();select(id);document.getElementById('model').scrollIntoView({behavior:reduced?'instant':'smooth'});});
function loop(time){if(playing){const dt=previous?Math.min((time-previous)/1000,.08):0;previous=time;state.progress=Math.min(parts.length,state.progress+dt/2.8);state.selected=state.progress?parts[activeStep(state.progress)-1].id:'';update();if(state.progress>=parts.length)pause();}controls?.update();if(dirty&&(renderer||time-lastVector>100)){render();dirty=false;lastVector=time;}requestAnimationFrame(loop);}requestAnimationFrame(loop);
